loading_screen_phase1 = ["MMMM   MMMM", "MMMMM MMMMM", "MMM MMM MMM", "MMM  M  MMM", "MMM     MMM", "MMM     MMM"]
loading_screen_phase2 = ["MMMM   MMMM       DDDDDD", "MMMMM MMMMM       DDDD  DDDD", "MMM MMM MMM       DDDD    DDD", "MMM  M  MMM       DDDD    DDD", "MMM     MMM       DDDD  DDDD", "MMM     MMM       DDDDDD"]
loading_screen_phase3 = ["MMMM   MMMM       DDDDDD           DDDDDD", "MMMMM MMMMM       DDDD  DDDD       DDDD  DDDD", "MMM MMM MMM       DDDD    DDD      DDDD    DDD", "MMM  M  MMM       DDDD    DDD      DDDD    DDD", "MMM     MMM       DDDD  DDDD       DDDD  DDDD", "MMM     MMM       DDDDDD           DDDDDD"]
main_menu_title = "MDD - Multidimensional Dungeons"
main_menu_new_game = "Neues Spiel"
main_menu_saved_game = "Gespeichertes Spiel"
main_menu_language = "Sprache"
main_menu_credits = "TXC & Co., Ltd."
language_menu_ru = "Русский"
language_menu_en = "English"
language_menu_de = "Deutsch"
language_menu_back = "Züruck"
restart_to_change_the_language_message = "Neustart zum Ändern der Sprache"
plot = """Seit Jahrhunderten führen primitive Stämme Krieg gegeneinander...
Die Barbaren wollten nur eines...
Zu zerstören...
Um alles und jeden zu zerstören...
Und niemand konnte Wissenschaft und Magie in ihrer ganzen Pracht verstehen...
Doch eines Tages geschah etwas, das die Geschichte veränderte...
Der Kriegsherr Hueret spazierte durch Wiesen, vor sechs Monaten mit dem Blut Feinde getränkt waren...
Er kam zu dem hohen Berg, wo das Gebiet seines Stammes endete...
Hueret wollte umkehren...
Aber er sah im Berg einen schmalen Durchgang, der tief führte...
In eine Höhle...
Die Neugierde überwand seine Angst vor dem Unbekannten und er betrat die Höhle...
Drinnen war es blendend hell, und Hueret bedeckte seine Augen mit der Hand...
Es war...
Der Mantel der Ewigkeit...
Ein uraltes Artefakt, geformt aus den Fäden des Chaos, das für das Gute genutzt werden könnte...
Oder für das Böse...
Hueret warf den Mantel über seine Schultern...
Sofort spürte er einen Schub an Kraft, trat aus der Höhle heraus und wandte sich der Stadt und seinem Heimatstamm zu...
Er trug den Mantel tagelang, nahm ihn nie ab und verspürte einen immer stärkeren Durst...
Der Durst der töten...
Der Mantel zügelte seinen Verstand, schickte gewalttätige Gedanken in ihn...
Was er befolgt...
Hueret wurde schnell der Herr seines Stammes...
Die ihm wegen seiner unglaublichen magischen Fähigkeiten gehorchten, die er vom Mantel erhalten hatte...
Er lernte, wie man Portale zu anderen Welten öffnet...
Oder magische Kreaturen und Waffen aus den Fäden des Chaos zu erschaffen...
Huerets Stamm gab sich den Namen Iraroth, was Herrschern bedeutet, und besiegte sehr schnell alle anderen Stämme...
Alle Kreaturen begannen sich zu teilen, in Iraroths, ihre Untergebenen und...
Menschen."""