loading_screen_phase1 = ["MMMM   MMMM", "MMMMM MMMMM", "MMM MMM MMM", "MMM  M  MMM", "MMM     MMM", "MMM     MMM"]
loading_screen_phase2 = ["MMMM   MMMM       DDDDDD", "MMMMM MMMMM       DDDD  DDDD", "MMM MMM MMM       DDDD    DDD", "MMM  M  MMM       DDDD    DDD", "MMM     MMM       DDDD  DDDD", "MMM     MMM       DDDDDD"]
loading_screen_phase3 = ["MMMM   MMMM       DDDDDD           DDDDDD", "MMMMM MMMMM       DDDD  DDDD       DDDD  DDDD", "MMM MMM MMM       DDDD    DDD      DDDD    DDD", "MMM  M  MMM       DDDD    DDD      DDDD    DDD", "MMM     MMM       DDDD  DDDD       DDDD  DDDD", "MMM     MMM       DDDDDD           DDDDDD"]
main_menu_title = "MDD - Multidimensional Dungeons"
main_menu_new_game = "New game"
main_menu_saved_game = "Saved game"
main_menu_language = "Language"
main_menu_credits = "TXC & Co., Ltd."
language_menu_ru = "Русский"
language_menu_en = "English"
language_menu_de = "Deutsch"
language_menu_back = "Back"
restart_to_change_the_language_message = "Restart to change the language"
plot = """For centuries primitive tribes have been at war with each other...
The barbarians wanted only one thing...
To destroy...
To destroy anything and everything...
And no one could understand science and magic in all their splendor...
But one day, something happened that changed history...
The warlord Huerat was strolling through meadows which were only six months ago drenched in the blood of his enemies...
He reached the high mountain where his tribe's lands ended...
Huerat would have turned back...
But he saw a narrow passageway in the mountain leading deeper...
Into a cave...
Curiosity overcame his fear of the unknown and he went in...
It was blindingly bright inside and Huerat shielded his eyes with his hand...
It was...
The Mantle of Eternity...
An ancient artifact formed from the strings of Сhaos that could be used for good...
Or for evil...
Huerat threw The Mantle over his shoulders...
He immediately felt a surge of strength, stepped out of the cave and turned his footsteps towards the city and his native tribe...
He wore The Mantle for days, never taking it off, and started to feel thirst more and more acutely...
A thirst for killing...
The Mantle obsessed his mind, sent cruel thoughts into him...
Which he obeyed...
Huerat quickly became the lord of his tribe...
Who admired him because of his incredible magical skills he received from The Mantle...
He learned how to open portals to other worlds...
Or create magical creatures and weapons from the strings of Chaos...
Huerat's tribe christened themselves Iraroth, which means Rulers, and very quickly defeated all the other tribes...
All creatures became divided into Iraroths, their subordinates and...
Humans."""